services:
  service-a:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: service-a
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - service-b
      - zipkin
    command: /app/service-a # Executa o binário do serviço A

  service-b:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: service-b
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
    command: /app/service-b # Executa o binário do serviço B

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
